apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline
  labels:
    app: pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
        - name: collector
          image: llana13/tweet-collector
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
          - name: collector-storage
            mountPath: /data/collector

        - name: mongodb
          image: mongo
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
            - name: mongo-persistent-volume
              mountPath: /mongo/data
          ports:
            - containerPort: 27017
        - name: etl-job
          image: llana13/etl-job
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
          - name: etl-storage
            mountPath: /data/etl

        - name: postgresdb
          image: postgres
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
            - name: postgres-persistent-volume
              mountPath: /postgres/data
          ports:
            - containerPort: 5432

      imagePullSecrets:
        - name: regcred
      volumes:
        - name: collector-storage
          emptyDir: {}

        - name: mongo-persistent-volume
          persistentVolumeClaim:
            claimName: mongo-claim
        - name: etl-storage
          emptyDir: {}

        - name: postgres-persistent-volume
          persistentVolumeClaim:
            claimName: postgres-claim

      nodeSelector:
        disktype: ssd
