apiVersion: v1
kind: Pod
metadata:
  name: etl
  labels:
    app: pipeline
spec:
  containers:
    - name: etl
      image: llana13/etl-job
      ports:
      - containerPort: 9876
        protocol: TCP
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
      - name: etl-storage
        mountPath: /data/etl
  volumes:
    - name: etl-storage
      emptyDir: {}
