apiVersion: v1
kind: Pod
metadata:
  name: postgresdb
  labels:
    app: pipeline
spec:
  containers:
    - name: postgresdb
      image: postgres
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - name: postgres-persistent-volume
          mountPath: /postgres/data
      ports:
        - containerPort: 5432
  volumes:
    - name: postgres-persistent-volume
      persistentVolumeClaim:
        claimName: postgres-claim
