apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persistent-volume
  labels:
    type: local
    app: pipeline
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/postgres/data"
