apiVersion: v1
kind: Pod
metadata:
  name: postgresdb
  labels:
    app: pipeline
spec:
  containers:
    - name: postgresdb
      image: postgres
      envFrom:
        - configMapRef:
            name: postgres-config
      volumeMounts:
        - name: postgres-persistent-volume
          mountPath: /postgres/data
      ports:
        - containerPort: 9876
  volumes:
    - name: postgres-persistent-volume
      persistentVolumeClaim:
        claimName: postgres-claim
