apiVersion: v1
kind: Pod
metadata:
  name: collector
  labels:
    app: pipeline
spec:
  containers:
    - name: collector
      image: llana13/tweet-collector
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
      - name: collector-storage
        mountPath: /data/collector
  volumes:
    - name: collector-storage
      emptyDir: {}
