apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: pipeline
spec:
  containers:
    - name: mongodb
      image: mongo

      volumeMounts:
        - name: mongo-persistent-volume
          mountPath: /mongo/data
      ports:
        - containerPort: 9876
  volumes:
    - name: mongo-persistent-volume
      persistentVolumeClaim:
        claimName: mongo-claim
