apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
  labels:
    app: hug
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
