apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-volume
  labels:
    type: local
    app: hug
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mongo/data"
