apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: pipeline
spec:
  containers:
    - name: mongodb
      image: mongo
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - name: mongo-persistent-volume
          mountPath: /mongo/data
      ports:
        - containerPort: 27017
  volumes:
    - name: mongo-persistent-volume
      persistentVolumeClaim:
        claimName: mongo-claim
