apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
  labels:
    app: pipeline
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
